doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        use_savepoints: true
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType
            ulid: Symfony\Bridge\Doctrine\Types\UlidType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        enable_lazy_ghost_objects: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App