vich_uploader:
    db_driver: orm

    mappings:
        documents:
            uri_prefix: /media/documents
            upload_destination: '%app.upload_dir%/%app.instance%/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        photos:
            uri_prefix: /media/photos
            upload_destination: '%app.upload_dir%/%app.instance%/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        branding:
            uri_prefix: /media/branding
            upload_destination: '%app.upload_dir%/%app.instance%/branding'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
