<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260906100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add downloadable document entity';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, visibility VARCHAR(32) NOT NULL, filename VARCHAR(255) NOT NULL, theme_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_document_visibility ON document (visibility)');
        $this->addSql('CREATE INDEX idx_document_theme ON document (theme_id)');
        $this->addSql('CREATE INDEX idx_document_date ON document (date)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT fk_document_theme FOREIGN KEY (theme_id) REFERENCES content_theme (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE document DROP CONSTRAINT fk_document_theme');
        $this->addSql('DROP TABLE document');
    }
}
