<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260827162511 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the site_settings singleton table and seed its unique row';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE site_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, site_name VARCHAR(120) NOT NULL, baseline VARCHAR(255) DEFAULT NULL, logo_filename VARCHAR(255) DEFAULT NULL, favicon_filename VARCHAR(255) DEFAULT NULL, contact_email VARCHAR(180) DEFAULT NULL, facebook_url VARCHAR(255) DEFAULT NULL, instagram_url VARCHAR(255) DEFAULT NULL, primary_color VARCHAR(7) NOT NULL, secondary_color VARCHAR(7) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        // Singleton guard: any attempt to insert a second row fails at the DB level.
        $this->addSql('ALTER TABLE site_settings ADD CONSTRAINT site_settings_singleton CHECK (id = 1)');
        $this->addSql("INSERT INTO site_settings (id, site_name, primary_color, secondary_color, updated_at) VALUES (1, 'OpenApel', '#272857', '#2ed8ff', NOW())");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE site_settings');
    }
}
