<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260903103000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add locked page catalogue and move homepage copy off site_settings';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(64) NOT NULL, title VARCHAR(180) NOT NULL, subtitle VARCHAR(255) DEFAULT NULL, body TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_page_slug ON page (slug)');

        $pages = [
            ['home', 'Accueil', null, null],
            ['news', 'Actualités', 'Les nouvelles de l\'association', null],
            ['agenda', 'Agenda', 'Découvrez tous les événements à venir et l\'historique de nos activités', null],
            ['faq', 'FAQ', 'Les questions les plus fréquentes des familles', null],
            ['team', 'Votre Équipe APEL', null, null],
            ['contact', 'Contact', 'Une question ? Écrivez-nous, nous vous répondrons dès que possible.', null],
            ['mentions-legales', 'Mentions légales', null, "À compléter par l'association.\n\nIndiquez l'éditeur du site, l'hébergeur et les mentions obligatoires."],
            ['politique-de-confidentialite', 'Politique de confidentialité', null, "À compléter par l'association.\n\nDécrivez les données collectées, leur usage et les droits des familles."],
        ];

        foreach ($pages as [$slug, $title, $subtitle, $body]) {
            $this->addSql(
                'INSERT INTO page (slug, title, subtitle, body, updated_at) VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)',
                [$slug, $title, $subtitle, $body],
            );
        }

        $this->addSql(<<<'SQL'
            UPDATE page
            SET
                title = COALESCE(NULLIF(TRIM(s.home_title), ''), NULLIF(TRIM(s.site_name), ''), page.title),
                body = NULLIF(TRIM(s.home_text), '')
            FROM site_settings s
            WHERE page.slug = 'home'
            SQL);

        $this->addSql('ALTER TABLE site_settings DROP home_title');
        $this->addSql('ALTER TABLE site_settings DROP home_text');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE site_settings ADD home_title VARCHAR(180) DEFAULT NULL');
        $this->addSql('ALTER TABLE site_settings ADD home_text TEXT DEFAULT NULL');
        $this->addSql(<<<'SQL'
            UPDATE site_settings
            SET home_title = p.title, home_text = p.body
            FROM page p
            WHERE p.slug = 'home'
            SQL);
        $this->addSql('DROP TABLE page');
    }
}
