<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260902084949 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE grade (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(32) NOT NULL, weight INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE school_class (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(32) NOT NULL, grade VARCHAR(16) NOT NULL, teacher VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE app_user ALTER weight DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE grade');
        $this->addSql('DROP TABLE school_class');
        $this->addSql('ALTER TABLE app_user ALTER weight SET DEFAULT 0');
    }
}
