<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260902155100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Replace post/faq theme enum columns with content_theme entity';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE content_theme (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(64) NOT NULL, icon VARCHAR(64) NOT NULL, weight INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_content_theme_name ON content_theme (name)');
        $this->addSql('CREATE INDEX idx_content_theme_weight ON content_theme (weight)');

        $this->addSql("INSERT INTO content_theme (name, icon, weight) VALUES
            ('Apprentissage', 'mdi-school', 80),
            ('Sport', 'mdi-soccer', 70),
            ('Culture', 'mdi-palette', 60),
            ('Alimentation', 'mdi-food-apple', 50),
            ('Extra scolaire', 'mdi-puzzle', 40),
            ('Pastorale', 'mdi-hands-pray', 30),
            ('APEL', 'mdi-account-group', 20),
            ('Autre', 'mdi-dots-horizontal-circle', 10)
        ");

        $this->addSql('ALTER TABLE post ADD theme_id INT');
        $this->addSql("UPDATE post SET theme_id = content_theme.id FROM content_theme WHERE content_theme.name = CASE post.theme
            WHEN 'apprentissage' THEN 'Apprentissage'
            WHEN 'sport' THEN 'Sport'
            WHEN 'culture' THEN 'Culture'
            WHEN 'alimentation' THEN 'Alimentation'
            WHEN 'extra_scolaire' THEN 'Extra scolaire'
            ELSE 'Autre'
        END");
        $this->addSql('ALTER TABLE post ALTER COLUMN theme_id SET NOT NULL');
        $this->addSql('DROP INDEX idx_post_theme');
        $this->addSql('ALTER TABLE post DROP theme');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT fk_post_theme FOREIGN KEY (theme_id) REFERENCES content_theme (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_post_theme ON post (theme_id)');

        $this->addSql('ALTER TABLE faq ADD theme_id INT');
        $this->addSql("UPDATE faq SET theme_id = content_theme.id FROM content_theme WHERE content_theme.name = CASE faq.theme
            WHEN 'apprentissage' THEN 'Apprentissage'
            WHEN 'sport' THEN 'Sport'
            WHEN 'culture' THEN 'Culture'
            WHEN 'alimentation' THEN 'Alimentation'
            WHEN 'extra_scolaire' THEN 'Extra scolaire'
            ELSE 'Autre'
        END");
        $this->addSql('ALTER TABLE faq ALTER COLUMN theme_id SET NOT NULL');
        $this->addSql('DROP INDEX idx_faq_theme');
        $this->addSql('ALTER TABLE faq DROP theme');
        $this->addSql('ALTER TABLE faq ADD CONSTRAINT fk_faq_theme FOREIGN KEY (theme_id) REFERENCES content_theme (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_faq_theme ON faq (theme_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE post DROP CONSTRAINT fk_post_theme');
        $this->addSql('DROP INDEX idx_post_theme');
        $this->addSql("ALTER TABLE post ADD theme VARCHAR(32) DEFAULT 'autre' NOT NULL");
        $this->addSql("UPDATE post SET theme = CASE content_theme.name
            WHEN 'Apprentissage' THEN 'apprentissage'
            WHEN 'Sport' THEN 'sport'
            WHEN 'Culture' THEN 'culture'
            WHEN 'Alimentation' THEN 'alimentation'
            WHEN 'Extra scolaire' THEN 'extra_scolaire'
            ELSE 'autre'
        END FROM content_theme WHERE content_theme.id = post.theme_id");
        $this->addSql('ALTER TABLE post ALTER COLUMN theme DROP DEFAULT');
        $this->addSql('ALTER TABLE post DROP theme_id');
        $this->addSql('CREATE INDEX idx_post_theme ON post (theme)');

        $this->addSql('ALTER TABLE faq DROP CONSTRAINT fk_faq_theme');
        $this->addSql('DROP INDEX idx_faq_theme');
        $this->addSql("ALTER TABLE faq ADD theme VARCHAR(32) DEFAULT 'autre' NOT NULL");
        $this->addSql("UPDATE faq SET theme = CASE content_theme.name
            WHEN 'Apprentissage' THEN 'apprentissage'
            WHEN 'Sport' THEN 'sport'
            WHEN 'Culture' THEN 'culture'
            WHEN 'Alimentation' THEN 'alimentation'
            WHEN 'Extra scolaire' THEN 'extra_scolaire'
            ELSE 'autre'
        END FROM content_theme WHERE content_theme.id = faq.theme_id");
        $this->addSql('ALTER TABLE faq ALTER COLUMN theme DROP DEFAULT');
        $this->addSql('ALTER TABLE faq DROP theme_id');
        $this->addSql('CREATE INDEX idx_faq_theme ON faq (theme)');

        $this->addSql('DROP TABLE content_theme');
    }
}
