<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260902162000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add contact_message table for public contact form submissions';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE contact_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, phone VARCHAR(40) DEFAULT NULL, subject VARCHAR(255) NOT NULL, message TEXT NOT NULL, processed BOOLEAN DEFAULT false NOT NULL, archived BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, school_class_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_contact_message_created_at ON contact_message (created_at)');
        $this->addSql('CREATE INDEX idx_contact_message_processed ON contact_message (processed)');
        $this->addSql('CREATE INDEX idx_contact_message_archived ON contact_message (archived)');
        $this->addSql('CREATE INDEX idx_contact_message_school_class ON contact_message (school_class_id)');
        $this->addSql('ALTER TABLE contact_message ADD CONSTRAINT fk_contact_message_school_class FOREIGN KEY (school_class_id) REFERENCES school_class (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE contact_message DROP CONSTRAINT fk_contact_message_school_class');
        $this->addSql('DROP TABLE contact_message');
    }
}
