import { library } from '@fortawesome/fontawesome-svg-core';
import { faFacebook, faInstagram } from '@fortawesome/free-brands-svg-icons';
import {
    faBan,
    faBars,
    faCalendarDays,
    faChevronLeft,
    faChevronRight,
    faCircleExclamation,
    faCircleQuestion,
    faClock,
    faDownload,
    faEnvelope,
    faFlag,
    faLocationDot,
    faMagnifyingGlass,
    faMasksTheater,
    faNewspaper,
    faPhone,
    faSchool,
    faTicket,
    faUmbrellaBeach,
    faUser,
    faUsers,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    faBan,
    faBars,
    faCalendarDays,
    faChevronLeft,
    faChevronRight,
    faCircleExclamation,
    faCircleQuestion,
    faClock,
    faDownload,
    faEnvelope,
    faFacebook,
    faFlag,
    faInstagram,
    faLocationDot,
    faMagnifyingGlass,
    faMasksTheater,
    faNewspaper,
    faPhone,
    faSchool,
    faTicket,
    faUmbrellaBeach,
    faUser,
    faUsers,
);
